name: Lint extra docsite docs and links
on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  push:
    branches:
      - main
      - stable-3.x
      - stable-4.x
  pull_request:
  # Run CI once per day (at 07:12 UTC)
  # This ensures that even if there haven't been commits that we are still testing against latest version of ansible-test for each ansible-base version
  schedule:
    - cron: '12 7 * * *'

jobs:
  docsite:
    name: Lint extra docsite docs and links
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install antsibull-docs
        run: pip install antsibull-docs --disable-pip-version-check

      - name: Install dependent collections
        run: >
          ansible-galaxy collection install
          'vmware.vmware>=1.10.0'

      - name: Run collection docs linter
        run: antsibull-docs lint-collection-docs . --plugin-docs --skip-rstcheck
